SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO AS II JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.ITEM_ID JOIN
ITEM_INFO AS PARENT_INFO ON IT.PARENT_ITEM_ID = PARENT_INFO.ITEM_ID
WHERE PARENT_INFO.RARITY = 'RARE'
ORDER BY II.ITEM_ID DESC;