-- 코드를 작성해주세요
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
WHERE 
1=1
AND
D.SKILL_CODE & (
SELECT CODE
FROM SKILLCODES
WHERE NAME = 'Python')
OR
D.SKILL_CODE & (
SELECT CODE
FROM SKILLCODES
WHERE NAME = 'C#')
ORDER BY D.ID;
