-- 코드를 작성해주세요
# SELECT HG.SCORE,HD.DEPT_NAME_KR AS EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
SELECT SUM(HG.SCORE) AS SCORE, HG.EMP_NO, HE.EMP_NAME, HE.POSITION,HE.EMAIL
FROM HR_DEPARTMENT AS HD JOIN HR_EMPLOYEES AS HE ON HD.DEPT_ID = HE.DEPT_ID JOIN HR_GRADE AS HG ON HE.EMP_NO = HG.EMP_NO
GROUP BY HG.EMP_NO 
ORDER BY SCORE DESC
LIMIT 1;